volumes:
  grafana-storage:  # "caché", interne à Docker
  airflow_home:

services:
  inference-api:
    build:
      context: .
      target: runtime
    environment:
      SPACY_N_PROCESS: "1"
      TZ: Europe/Paris
      SMALL_DATASET_FOR_DEBUGGING: "false"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - .:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').getcode()"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 5s

  tests:
    build:
      context: .
      target: test
    environment:
      API_BASE_URL: "http://inference-api:8000"
      SPACY_N_PROCESS: "1"
      TZ: Europe/Paris
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - .:/app
    depends_on:
      inference-api:
        condition: service_healthy

  streamlit:
    build:
      context: .
      target: streamlit
    command: streamlit run src/streamlit/app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      API_BASE_URL: "http://inference-api:8000"
      TZ: Europe/Paris
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - .:/app
    depends_on:
      inference-api:
        condition: service_healthy

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.11.1
    command: mlflow server --backend-store-uri /mlruns --host 0.0.0.0 --port 5000 --allowed-hosts "*"
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlruns

  prometheus:
    image: prom/prometheus:v3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  airflow:
    image: apache/airflow:2.9.3
    container_name: rakuten-airflow
    command: standalone
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW_CONN_TRAINING_API: '{"conn_type": "http", "host": "inference-api", "port": 8000}'
      AIRFLOW_INTERVAL_MINUTES: "15"  # "1" is ok if you set `SMALL_DATASET_FOR_DEBUGGING="true"` for `inference-api` above
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_home:/opt/airflow
    ports:
      - "8080:8080"
