services:
  inference-api:
    build: .
    environment:
      SPACY_N_PROCESS: "1"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # override dockerfile CMD with --reload for dev
